apiVersion: v1
kind: Service
metadata:
  name: gift-recommender-service
  labels:
    app: gift-recommender-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    app: gift-recommender-service
